### ISSUE TITLE
[Emulator Request] suyu

### ISSUE THREAD

**Issue by CCIGAMES** [kleidis/Troppical#22]
**Emulator Name**
suyu

**GitHub URL**
[Put the repo's URL here](https://github.com/suyu-emu/suyu)
or
[Put the repo's URL here](https://git.suyu.dev/suyu/suyu)

** Have you confirmed the emulator doesn't have a built-in updater?**
[*no*]

** Have you confirmed the emulator is distributed through Github releases?**
[*partly, its on both github and its own git*]

**Comment by kleidis** [comment]
As you said it is distributed through their own self-hosted Git repo. The problem is we use the GitHub API to download emulators from assets on releases and Suyu doesn't actually publish releases to Github but just links to their own Git Repo assets
As of now Troppicla only supports Github releases but that might change soon as we want to add emulators from outside Github as well
![image](https://github.com/kleidis/Troppical/assets/167202775/764df6af-22f1-4628-bcb2-3ce2be7c50b5)

**Comment by CCIGAMES** [comment]
thanks, if ur planning on getting it to receive releases outside of github, suyu's git is the best place to start imo as the git is already super close to github
